{-
   httpstan

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   httpstan API version: 4.10.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Httpstan.API
-}

module Httpstan.API
  ( module Httpstan.API.ApiDefault
  ) where

import Httpstan.API.ApiDefault